repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-merge-conflict  # checks for files that contain merge conflict strings
  - id: check-toml  # checks toml files for parseable syntax
  - id: debug-statements  # checks for debugger imports and py37+ `breakpoint()` calls in python source
