name: workflow

on:
  push:
    branches-ignore:
      - 'stable'
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install OOMMF
      run: conda install --channel conda-forge oommf

    - name: Install testing packages
      run: python -m pip install --upgrade pip pytest-cov nbval pycodestyle

    - name: Install ubermag dependencies
      run: |
        python -m pip install git+https://github.com/ubermag/ubermagutil.git
        python -m pip install git+https://github.com/ubermag/discretisedfield.git
        python -m pip install git+https://github.com/ubermag/ubermagtable.git
        python -m pip install git+https://github.com/ubermag/micromagneticmodel.git
        python -m pip install git+https://github.com/ubermag/micromagneticmodel.git
        python -m pip install git+https://github.com/ubermag/micromagnetictests.git

    - name: Install package
      run: python -m pip install .

    - name: Unit tests
      run: make test-unittests

    - name: Documentation tests
      run: make test-docs

    - name: Jupyter notebook tests
      run: make test-ipynb
      if: matrix.os != 'windows-latest'

    - name: Python code style
      run: make test-pycodestyle

    # - name: Tests coverage
    #   run: make test-coverage
    #   if: matrix.os == 'ubuntu-latest'

    # - name: Upload coverage to Codecov.io
    #   uses: codecov/codecov-action@v1
    #   if: matrix.os == 'ubuntu-latest'
